// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	TRUSTED_ORIGINS: ["http://localhost:3001"];
	BETTER_AUTH_SECRET: "secret";
	BETTER_AUTH_BASE_URL: "http://localhost:3000";
	DB: D1Database;
}
